[package]
name = "xactlyblue/sketch"
description = "A simple solution to visual debugging in Roblox."
version = "1.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
homepage = "https://xactlyblue.github.io/sketch"
realm = "shared"
authors = [ "xactlyblue" ]
exclude = [ "docs", ".moonwave", "build", "pages" ]
include = [ "src" ]
